name: Build and Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy CarCatch web application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }} #ipv4 address of droplet
          key: ${{ secrets.SSH_KEY }} #Private or public key of server
          username: ${{ secrets.SSH_USERNAME }} #Name of user on droplet
          port: ${{ secrets.SSH_PORT }} #port to ssh on (default)
          script: echo 'Deployment to digitalocean droplet CarCatch is successful'
     
